insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (1, 'Ingmar', 'wJ7J0Xap');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (2, 'Michail', 'wM6o<');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (3, 'Stan', 'wS5#L{@');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (4, 'Annamarie', 'eB9.n');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (5, 'Tonnie', 'kV2%F');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (6, 'Falito', 'sJ5S');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (7, 'Lyssa', 'eW5us`');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (8, 'Kelcey', 'yT7)WP/');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (9, 'Madlen', 'lH7OQ''CD');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (10, 'Rockie', 'cS5hC');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (11, 'Sophi', 'kF8wPY0N');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (12, 'Maximilianus', 'bU1ypWu\');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (13, 'Harlen', 'mL7JMq{');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (14, 'Else', 'aS8$S');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (15, 'Wilie', 'wS0&e');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (16, 'Kareem', 'fP0$');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (17, 'Archy', 'mF3l');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (18, 'Katherine', 'bB3&D');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (19, 'Bernetta', 'kF5j=YwG');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (20, 'Jedd', 'qI2QvU');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (21, 'Selia', 'mW97\{X');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (22, 'Maude', 'cF9M');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (23, 'Maria', 'qJ8`');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (24, 'Arnold', 'oD1t''');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (25, 'Toby', 'gV6Rm2zY');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (26, 'Natale', 'lD5,');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (27, 'Trudie', 'oD2$!');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (28, 'Ingeberg', 'wG2W');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (29, 'Maxine', 'iQ4Dq3A');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (30, 'Torrey', 'dH1sFR');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (31, 'Barbette', 'fO9PZS');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (32, 'Josepha', 'dT9xM');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (33, 'Herold', 'oX2JAR5O');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (34, 'Arleta', 'hL1#eV3_');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (35, 'Archambault', 'bO5Xi');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (36, 'Corby', 'kZ3a');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (37, 'Charmain', 'kE2y?');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (38, 'Shari', 'uG9,v)N5');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (39, 'Karlis', 'eK5Mw');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (40, 'Bee', 'pS4=');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (41, 'Hyacinthie', 'dL1,''');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (42, 'Taryn', 'qZ2@');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (43, 'Nat', 'eT1r`Oc');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (44, 'Tarrance', 'lL72xWi');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (45, 'Palmer', 'lW7V');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (46, 'Brier', 'yX4zr');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (47, 'Ara', 'kQ3~Tl/2');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (48, 'Lucita', 'qX1,');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (49, 'Yvonne', 'rB5MF4Hi');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (50, 'Dion', 'tO7&T');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (51, 'David', 'aX1zlob,');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (52, 'Jaime', 'eJ1f(Pgd');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (53, 'Hasheem', 'sJ4|3#Q');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (54, 'Kristen', 'pQ0tU');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (55, 'Lorita', 'lQ1Y\4');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (56, 'Hayes', 'sF0F');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (57, 'Leonanie', 'rV9Q|');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (58, 'Orin', 'nA2`79yP');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (59, 'Ginger', 'oJ86\7?2');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (60, 'Arthur', 'fD2V');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (61, 'Florentia', 'hN7o');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (62, 'Vanya', 'nL5!<0');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (63, 'Paul', 'oC7#>|');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (64, 'Lilllie', 'sP4DlQ');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (65, 'Forbes', 'zA3V."');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (66, 'Billye', 'cM59q');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (67, 'Arlinda', 'yY3f|');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (68, 'Mortie', 'dC3''g');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (69, 'Gustavus', 'nW05\YN');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (70, 'Juliana', 'tN0U');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (71, 'Jackie', 'tY7jK2`');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (72, 'Celinka', 'pJ5W8(k');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (73, 'Griswold', 'lL2.kMzD');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (74, 'Petunia', 'rE6os\7s');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (75, 'Charlie', 'yM7h');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (76, 'Englebert', 'vA0P\');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (77, 'Tatiana', 'kG3*d3Y(');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (78, 'Artur', 'iY8&ygyN');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (79, 'Bernardo', 'pC5=');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (80, 'Jeffry', 'dB5OP');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (81, 'Shalom', 'zA1COZw');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (82, 'Charles', 'rG2''z');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (83, 'Revkah', 'uD3nJ');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (84, 'Samara', 'lD1}JMC');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (85, 'Doe', 'xJ73');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (86, 'Valentino', 'eI1i');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (87, 'Tome', 'vO3A~ktg');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (88, 'Kriste', 'tR5qw');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (89, 'Wilmette', 'uD071yT');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (90, 'Alleyn', 'sF9#');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (91, 'Daven', 'zT5"''KG');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (92, 'Megen', 'lB0''');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (93, 'Jules', 'pW0nQs');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (94, 'Norene', 'jW6Kj');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (95, 'Sal', 'pV6RpC');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (96, 'Josephine', 'iP6SR+)K');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (97, 'Iolande', 'wQ6l');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (98, 'Fritz', 'rE2iYJ\o');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (99, 'Marti', 'jT97BL');
insert into usuario (id_usuario , nombre_usuario, contrasenia_usuario) values (100, 'Carver', 'vP8|b');

insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (1, 'Trotar', 'Trotar 15 Km', '04-12-2022', 'En progreso', 6);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (2, 'Leer un libro', 'Leer 10 páginas', '03-08-2023', 'En progreso', 90);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (3, 'Lavar ropa', 'Lavar ropa sucia de la semana', '31-01-2023', 'En progreso', 67);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (4, 'Cocinar', 'Cocinar la cena', '18-06-2023', 'Pendiente', 23);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (5, 'Publicar vídeo', 'Publicar videos en redes sociales', '16-11-2022', 'En progreso', 17);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (6, 'Dormir siesta', 'Descansar 1 hora', '10-05-2023', 'En progreso', 53);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (7, 'Llamar a un amigo', 'Llamar a mi amigo por su cumpleaños', '19-06-2023', 'En progreso', 46);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (8, 'Comprar comida', 'Comprar provisiones para la semana', '01-01-2023', 'Completada', 89);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (9, 'Ver una serie', 'Ver la nueva serie popular', '20-07-2023', 'Completada', 67);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (10, 'Limpiar la casa', 'Limpiar cocina y baño', '21-11-2022', 'Completada', 17);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (11, 'Ir a clases', 'Ir a clases en la universidad', '17-06-2023', 'En progreso', 48);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (12, 'Hacer tareas', 'Hacer la tarea de matemáticas', '24-10-2023', 'Pendiente', 44);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (13, 'Practicar guitarra', 'Practicar lamento boliviano en guitarra', '03-10-2022', 'Pendiente', 49);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (14, 'Visitar abuelos', 'Visitar a los abuelos y llevarles regalos', '16-06-2023', 'Completada', 75);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (15, 'Probar nueva receta', 'Probar nueva receta de pollo frito', '13-12-2022', 'Completada', 90);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (16, 'Ordenar closet', 'Separar ropa de invierno y verano', '05-01-2023', 'En progreso', 11);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (17, 'Donar alimentos', 'Donar alimentos no perecibles', '03-12-2022', 'Completada', 37);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (18, 'Proyecto escolar', 'Avanzar en el proyecto escolar', '22-06-2023', 'En progreso', 45);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (19, 'Clases de ajedrez', 'Entrenamiento de ajedrez', '14-09-2023', 'Completada', 95);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (20, 'Pintar paisaje', 'Pintar un paisaje para la clase de artes', '10-10-2022', 'Completada', 18);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (21, 'Trotar', 'Trotar 15 Km', '20-08-2023', 'Pendiente', 76);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (22, 'Leer un libro', 'Leer 10 páginas', '21-04-2023', 'Pendiente', 80);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (23, 'Lavar ropa', 'Lavar ropa sucia de la semana', '25-09-2023', 'Pendiente', 6);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (24, 'Cocinar', 'Cocinar la cena', '29-09-2023', 'Pendiente', 72);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (25, 'Publicar vídeo', 'Publicar videos en redes sociales', '24-10-2022', 'Pendiente', 24);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (26, 'Dormir siesta', 'Descansar 1 hora', '03-03-2023', 'Completada', 39);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (27, 'Llamar a un amigo', 'Llamar a mi amigo por su cumpleaños', '16-06-2023', 'Pendiente', 5);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (28, 'Comprar comida', 'Comprar provisiones para la semana', '29-03-2023', 'Completada', 18);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (29, 'Ver una serie', 'Ver la nueva serie popular', '16-05-2023', 'En progreso', 34);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (30, 'Limpiar la casa', 'Limpiar cocina y baño', '13-12-2022', 'En progreso', 85);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (31, 'Ir a clases', 'Ir a clases en la universidad', '25-12-2022', 'Completada', 20);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (32, 'Hacer tareas', 'Hacer la tarea de matemáticas', '31-12-2022', 'Completada', 9);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (33, 'Practicar guitarra', 'Practicar lamento boliviano en guitarra', '28-02-2023', 'Completada', 3);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (34, 'Visitar abuelos', 'Visitar a los abuelos y llevarles regalos', '28-11-2022', 'En progreso', 81);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (35, 'Probar nueva receta', 'Probar nueva receta de pollo frito', '02-10-2023', 'Pendiente', 39);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (36, 'Ordenar closet', 'Separar ropa de invierno y verano', '29-11-2022', 'Pendiente', 68);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (37, 'Donar alimentos', 'Donar alimentos no perecibles', '17-07-2023', 'En progreso', 97);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (38, 'Proyecto escolar', 'Avanzar en el proyecto escolar', '24-07-2023', 'Pendiente', 90);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (39, 'Clases de ajedrez', 'Entrenamiento de ajedrez', '07-04-2023', 'Completada', 59);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (40, 'Pintar paisaje', 'Pintar un paisaje para la clase de artes', '14-11-2022', 'Pendiente', 19);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (41, 'Trotar', 'Trotar 15 Km', '11-01-2023', 'En progreso', 100);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (42, 'Leer un libro', 'Leer 10 páginas', '13-10-2023', 'Completada', 39);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (43, 'Lavar ropa', 'Lavar ropa sucia de la semana', '23-09-2023', 'Completada', 38);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (44, 'Cocinar', 'Cocinar la cena', '23-06-2023', 'Completada', 8);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (45, 'Publicar vídeo', 'Publicar videos en redes sociales', '22-05-2023', 'Pendiente', 75);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (46, 'Dormir siesta', 'Descansar 1 hora', '31-08-2023', 'Completada', 91);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (47, 'Llamar a un amigo', 'Llamar a mi amigo por su cumpleaños', '08-03-2023', 'Completada', 40);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (48, 'Comprar comida', 'Comprar provisiones para la semana', '06-06-2023', 'En progreso', 81);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (49, 'Ver una serie', 'Ver la nueva serie popular', '06-05-2023', 'En progreso', 18);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (50, 'Limpiar la casa', 'Limpiar cocina y baño', '06-03-2023', 'Pendiente', 91);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (51, 'Ir a clases', 'Ir a clases en la universidad', '28-01-2023', 'Pendiente', 6);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (52, 'Hacer tareas', 'Hacer la tarea de matemáticas', '17-02-2023', 'Pendiente', 34);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (53, 'Practicar guitarra', 'Practicar lamento boliviano en guitarra', '13-01-2023', 'Completada', 58);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (54, 'Visitar abuelos', 'Visitar a los abuelos y llevarles regalos', '21-04-2023', 'Completada', 48);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (55, 'Probar nueva receta', 'Probar nueva receta de pollo frito', '24-08-2023', 'Completada', 62);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (56, 'Ordenar closet', 'Separar ropa de invierno y verano', '17-10-2022', 'En progreso', 44);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (57, 'Donar alimentos', 'Donar alimentos no perecibles', '08-06-2023', 'Pendiente', 72);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (58, 'Proyecto escolar', 'Avanzar en el proyecto escolar', '15-12-2022', 'Pendiente', 76);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (59, 'Clases de ajedrez', 'Entrenamiento de ajedrez', '27-04-2023', 'En progreso', 35);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (60, 'Pintar paisaje', 'Pintar un paisaje para la clase de artes', '05-04-2023', 'En progreso', 12);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (61, 'Trotar', 'Trotar 15 Km', '03-03-2023', 'Pendiente', 29);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (62, 'Leer un libro', 'Leer 10 páginas', '17-11-2022', 'Pendiente', 42);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (63, 'Lavar ropa', 'Lavar ropa sucia de la semana', '08-10-2023', 'En progreso', 86);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (64, 'Cocinar', 'Cocinar la cena', '24-12-2022', 'Pendiente', 48);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (65, 'Publicar vídeo', 'Publicar videos en redes sociales', '01-01-2023', 'Completada', 29);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (66, 'Dormir siesta', 'Descansar 1 hora', '06-03-2023', 'Completada', 78);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (67, 'Llamar a un amigo', 'Llamar a mi amigo por su cumpleaños', '19-11-2022', 'Pendiente', 70);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (68, 'Comprar comida', 'Comprar provisiones para la semana', '01-05-2023', 'Completada', 67);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (69, 'Ver una serie', 'Ver la nueva serie popular', '14-06-2023', 'Completada', 89);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (70, 'Limpiar la casa', 'Limpiar cocina y baño', '23-02-2023', 'Completada', 11);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (71, 'Ir a clases', 'Ir a clases en la universidad', '12-10-2022', 'Completada', 77);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (72, 'Hacer tareas', 'Hacer la tarea de matemáticas', '05-03-2023', 'Completada', 16);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (73, 'Practicar guitarra', 'Practicar lamento boliviano en guitarra', '03-05-2023', 'En progreso', 30);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (74, 'Visitar abuelos', 'Visitar a los abuelos y llevarles regalos', '18-03-2023', 'Completada', 53);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (75, 'Probar nueva receta', 'Probar nueva receta de pollo frito', '31-03-2023', 'Completada', 46);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (76, 'Ordenar closet', 'Separar ropa de invierno y verano', '14-08-2023', 'Pendiente', 13);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (77, 'Donar alimentos', 'Donar alimentos no perecibles', '09-01-2023', 'Completada', 97);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (78, 'Proyecto escolar', 'Avanzar en el proyecto escolar', '02-09-2023', 'Pendiente', 6);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (79, 'Clases de ajedrez', 'Entrenamiento de ajedrez', '08-10-2022', 'En progreso', 42);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (80, 'Pintar paisaje', 'Pintar un paisaje para la clase de artes', '01-11-2022', 'En progreso', 6);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (81, 'Trotar', 'Trotar 15 Km', '16-06-2023', 'Pendiente', 75);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (82, 'Leer un libro', 'Leer 10 páginas', '17-04-2023', 'Completada', 26);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (83, 'Lavar ropa', 'Lavar ropa sucia de la semana', '06-02-2023', 'Pendiente', 75);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (84, 'Cocinar', 'Cocinar la cena', '20-02-2023', 'En progreso', 29);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (85, 'Publicar vídeo', 'Publicar videos en redes sociales', '23-04-2023', 'Pendiente', 5);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (86, 'Dormir siesta', 'Descansar 1 hora', '09-11-2022', 'En progreso', 50);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (87, 'Llamar a un amigo', 'Llamar a mi amigo por su cumpleaños', '01-06-2023', 'Pendiente', 85);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (88, 'Comprar comida', 'Comprar provisiones para la semana', '06-12-2022', 'Pendiente', 83);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (89, 'Ver una serie', 'Ver la nueva serie popular', '08-01-2023', 'En progreso', 95);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (90, 'Limpiar la casa', 'Limpiar cocina y baño', '11-09-2023', 'Pendiente', 55);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (91, 'Ir a clases', 'Ir a clases en la universidad', '14-11-2022', 'Completada', 68);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (92, 'Hacer tareas', 'Hacer la tarea de matemáticas', '23-12-2022', 'Pendiente', 45);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (93, 'Practicar guitarra', 'Practicar lamento boliviano en guitarra', '02-08-2023', 'Completada', 10);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (94, 'Visitar abuelos', 'Visitar a los abuelos y llevarles regalos', '20-06-2023', 'Completada', 52);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (95, 'Probar nueva receta', 'Probar nueva receta de pollo frito', '11-06-2023', 'Pendiente', 10);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (96, 'Ordenar closet', 'Separar ropa de invierno y verano', '23-06-2023', 'En progreso', 46);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (97, 'Donar alimentos', 'Donar alimentos no perecibles', '16-09-2023', 'Pendiente', 83);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (98, 'Proyecto escolar', 'Avanzar en el proyecto escolar', '07-08-2023', 'Pendiente', 82);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (99, 'Clases de ajedrez', 'Entrenamiento de ajedrez', '21-10-2023', 'Completada', 78);
insert into tarea (id_tarea, nombre_tarea, desc_tarea, vence_tarea, estado_tarea, id_usuario_tarea) values (100, 'Pintar paisaje', 'Pintar un paisaje para la clase de artes', '17-12-2022', 'Completada', 5);
